apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - name: customer
          image: "amigoscode/kubernetes:customer-v1"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: ORDER_SERVICE
              # value: "10.244.1.15:8081" # if we use `port-forward`, then this will break after pod dies
              value: "order:8084" # this is Service name and Service outbound port. `order` is DNS
          ports:
            - containerPort: 8080

---
#
#apiVersion: v1
#kind: Service
#metadata:
#  name: customer-node
#spec:
#  type: NodePort # it makes this service available on all nodes
#  selector:
#    app: customer # need to match name of the pod from labels
#  ports:
#    - port: 8089
#      targetPort: 8080
#      nodePort: 30002 # opens up port on all nodes. It will accept incoming request and then forward to port (8089 in our case)
