apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-java-deploy
spec:
  replicas: 3
  revisionHistoryLimit: 7
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: order-java-deploy # ReplicaSet will manage everything that match this label
  template:
    metadata:
      labels:
        app: order-java-deploy # this deploy will be tied to any pod that has label of `order`
    spec:
      containers:
        - name: order-java-deploy
          image: "enoshima/springboot-k8s-order:latest"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8090 # this one should match PORT of the app server

--- # this means new resource
apiVersion: v1
kind: Service
metadata:
  name: order-java # name of the Service
spec:
  type: ClusterIP
  selector:
    app: order-java-deploy # this will match to the pods above. label: key - value
  ports:
    - port: 8085
      targetPort: 8090 # port of the target container
